//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestVmWareAPI.EFDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_HORIZON_VIEW
    {
        public string HORIZON_UUID { get; set; }
        public string HORIZON_NAME { get; set; }
        public string HORIZON_NAME_EN { get; set; }
        public string HORIZON_URL { get; set; }
        public string HORIZON_IP { get; set; }
        public Nullable<short> HORIZON_PORT { get; set; }
        public string DESCRIPTION { get; set; }
        public string ADMIN_ID { get; set; }
        public string ADMIN_PW { get; set; }
        public string NCC_SERVICE_IP { get; set; }
        public short NCC_SERVICE_PORT { get; set; }
        public string REG_ADMIN_ID { get; set; }
        public System.DateTime REG_DATETIME { get; set; }
        public string UPDATE_ADMIN_ID { get; set; }
        public System.DateTime UPDATE_DATETIME { get; set; }
        public bool DEL_YN { get; set; }
    }
}
